<?php

use paragraph1\phpFCM\Client;
use paragraph1\phpFCM\Message;
use paragraph1\phpFCM\Recipient\Topic;
use paragraph1\phpFCM\Notification;

require_once 'vendor/autoload.php';

function fcm_node_update($node){
    $apiKey = 'AAAAui1IzmE:APA91bEqjOebLbA99cwnvAIZUJWqz430-BuomrzfUJpIhCbotKlABBNP9Pmw4IMgL-TS5aO5BUltcUZUCuuypS8ZofF0fOq0YPIVDTPdQPC4Amu1CDIXCsQzCdl_QUgafEEqXG-IMYFQ';
    $client = new Client();
    $client->setApiKey($apiKey);
    $client->injectHttpClient(new \GuzzleHttp\Client());

    if ($node->type == 'kastenzettel_aetna'){
        $message = new Message();
        $message->addRecipient(new Topic('any'));
        $message->addRecipient(new Topic('aetna'));
        $message->setNotification(new Notification('Kastenzettel Aetna','Der Kastenzettel vom Stamm Aetna wurde aktualisiert.'));

        $response = $client->send($message);

        if ($response->getStatusCode() == 200) {
            drupal_set_message("Es wurde eine Benachrichtigung an alle App-Nutzer gesendet!", 'status');
        }
    }elseif ($node->type == 'kastenzettel_saturn'){
        $message = new Message();
        $message->addRecipient(new Topic('any'));
        $message->addRecipient(new Topic('saturn'));
        $message->setNotification(new Notification('Kastenzettel Saturn','Der Kastenzettel vom Trupp Saturn wurde aktualisiert.'));

        $response = $client->send($message);

        if ($response->getStatusCode() == 200) {
            drupal_set_message("Es wurde eine Benachrichtigung an alle App-Nutzer gesendet!", 'status');
        }
    }elseif ($node->type == 'kastenzettel_wolf'){
        $message = new Message();
        $message->addRecipient(new Topic('any'));
        $message->addRecipient(new Topic('wolf'));
        $message->setNotification(new Notification('Kastenzettel Phönix','Der Kastenzettel der Meute Phönix wurde aktualisiert.'));

        $response = $client->send($message);

        if ($response->getStatusCode() == 200) {
            drupal_set_message("Es wurde eine Benachrichtigung an alle App-Nutzer gesendet!", 'status');
        }
    }elseif ($node->type == 'kastenzettel_biber'){
        $message = new Message();
        $message->addRecipient(new Topic('any'));
        $message->addRecipient(new Topic('biber'));
        $message->setNotification(new Notification('Kastenzettel Biberstein','Der Kastenzettel der Familie Biberstein wurde aktualisiert.'));

        $response = $client->send($message);

        if ($response->getStatusCode() == 200) {
            drupal_set_message("Es wurde eine Benachrichtigung an alle App-Nutzer gesendet!", 'status');
        }
    }
}
